---
title: "Questão 3"
author: "Hermes"
date: "08/09/2021"
output: html_document
---

```{r setup, include=FALSE}
options(scipen = 999)
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load(dplyr, stringr, scales)

sim_consolidado <- readRDS("../data/sim/sim_consolidado.rds")
sinasc_consolidado <- readRDS("../data/sinasc/sinasc_consolidado.rds")

sim_consolidado$ANO_OBITO <- sim_consolidado$DTOBITO %>% str_extract('(?<=[0-9]{4})[0-9]{4}')
sinasc_consolidado$ANO_NASC <- sinasc_consolidado$DTNASC %>% str_extract('(?<=[0-9]{4})[0-9]{4}')


```

## Questão 3: Mortalidade


### b) Calcule a TMI, utilizando o número médio de óbitos ocorridos entre 2018 e 2020 e o número de nascimentos de 2019. Calcule os indicadores: taxa de mortalidade neonatal, neonatal precoce, neonatal tardia, posneonatal. Agregando a informação sobre óbitos fetais para os mesmos anos, calcule a taxa de mortalidade perinatal.


```{r}
sim_b <- sim_consolidado %>% filter(ANO_OBITO >=2018  & ANO_OBITO<=2020)

```

```{r}

nascimentos_19 <- sinasc_consolidado %>% filter(ANO_NASC == 2019) %>% length()

# Menor que 1 ano de idade
mortes_infantil_18_20 <- filter(sim_b,as.numeric(as.character(sim_b$IDADE))<= 400) %>%  nrow()
TMI <- (mortes_infantil_18_20/3)/nascimentos_19

# Menor que 28 dias de idade
mortes_neotal_18_20 <- filter(sim_b,as.numeric(as.character(sim_b$IDADE))<= 301) %>% nrow()
tx_mort_neotal <- (mortes_neotal_18_20/3)/nascimentos_19

# Menor que 1 semana de vida
mortes_neotal_prec_18_20 <- filter(sim_b,as.numeric(as.character(sim_b$IDADE))<= 207) %>% nrow()
tx_mort_neotal_precoce <- (mortes_neotal_prec_18_20/3)/nascimentos_19

# 1 semana a 1 mes de vida
mortes_neotal_tard_18_20 <- filter(sim_b,as.numeric(as.character(sim_b$IDADE))<= 301 & 
                                     as.numeric(as.character(sim_b$IDADE))> 207) %>% nrow()
tx_mort_neotal_tardia <- (mortes_neotal_tard_18_20/3)/nascimentos_19

# 1 mes a 1 ano de vida
mortes_posneotal_18_20 <- filter(sim_b,as.numeric(as.character(sim_b$IDADE))<= 400 & 
                                     as.numeric(as.character(sim_b$IDADE))>= 301) %>% nrow()
tx_mort_posneotal <- (mortes_posneotal_18_20/3)/nascimentos_19

# de 22 semanas de gestação a 7 dias de vida

mortes_neotal_perinatal <- filter(sim_b,as.numeric(as.character(sim_b$IDADE))<= 207) %>% nrow()
mortes_neotal_perinatal <- mortes_neotal_perinatal + filter(sim_b,as.numeric(as.character(sim_b$SEMAGESTAC))>= 22) %>% nrow()

tx_mort_neotal_perinatal <- (mortes_neotal_perinatal/3)/nascimentos_19

# antes do nascimento
obitos_fetais <- filter(sim_b,as.numeric(as.character(sim_b$TIPOBITO))== 1) %>% nrow()

tx_mort_obitos_fetais <- (obitos_fetais/3)/nascimentos_19
  
TMI
tx_mort_neotal
tx_mort_neotal_precoce
tx_mort_neotal_tardia
tx_mort_posneotal
tx_mort_neotal_perinatal
tx_mort_obitos_fetais    


sim_consolidado$IDADE %>% summary()
```

